#!/bin/bash


HOSTNAME=Arch-Death-Ray-Blaster

packages="git cowsay automake gdb vim firefox nmap nvidia ngrok make sudo NetworkManager 
            tmux virt-manager grub efibootmgr xorg-server xorg-apps xorg i3-wm"

vim_plugins="vim-scripts/DoxygenToolkit.vim wikitopian/hardmode nathanaelkane/vim-indent-guides scrooloose/nercommenter airblade/vim-gitgutter tibabit/vim-templates haya14busa/incsearch.vim scrooloose/nerdtree itchyny/lightline.vim octol/vim-cpp-enhanced-highlight"

house-keeping () {
    # Update system clock
    timedatectl set-ntp true
    # Symbolic link to etc localtime
    ln -sf /usr/share/zoneinfo/US/Mountain /etc/localtime
    # generate /etc/adjtime
    hwclock --systohc
    # Change the local time configuration
    sed 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' locale.gen -i
    locale-gen
    touch /etc/hostname
    echo "$HOSTNAME" >> /etc/hostname

    echo "127.0.0.1         localhost" >> /etc/hosts
    echo "::1               localhost" >> /etc/hosts
    echo "127.0.1.1         $HOSTNAME.localdomain   $HOSTNAME" >> /etc/hosts

    # Create initramfs
    mkinitcpio -p linux
}

install-packages () {
    pacstrap /mnt base
    pacstrap /mnt $packages
    nvidia-xconfig
}

boot-loader () { 
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
    grub-mkconfig -o /boot/grub/grub.cfg
}

administration () {
    echo "Create a password for root"
    passwd
    useradd -m theo
    echo "Create a password for theo"
    passwd theo
    echo "theo ALL=(ALL) ALL" >> /etc/sudoers
}

github () {
    for i in ${vim_plugins[*]};
    do
        git clone https://github.com/$i.git
    done

}



github
